security:
  oauth2:
    client:
      clientId: replace-with-your-client-id
      clientSecret: replace-with-your-client-secret
      scope: profile, email, https://www.googleapis.com/auth/drive
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me